Made a POJO Room with enum and RoomType class.
Cap-SE-Training/Hotel pull request #1
Opened 2018-01-16 13:39 UTC by IanNelissen

Room class

2018-01-16 14:16 UTC, AvantHof commented on src/main/java/com/capgemini/setrack/Model/Room.java
> +    private String number;
Waarom is de nummer een string? Als het een nummer is kan het int/long zijn, als het een naam is moet de variabele anders heten.

2018-01-16 14:19 UTC, AvantHof requested changes

2018-01-16 14:19 UTC, AvantHof commented on src/main/java/com/capgemini/setrack/Model/Room.java
> +    private RoomStatus roomStatus;
roomStatus default zetten op available.

2018-01-16 14:19 UTC, AvantHof commented on src/main/java/com/capgemini/setrack/Model/Enums/RoomStatus.java
> +    AVALIABLE,
Typfout

2018-01-17 10:27 UTC, jimmy1993k commented on src/main/java/com/capgemini/setrack/Model/Room.java
> +    private RoomStatus roomStatus;
Wordt gedaan op line 21

2018-01-18 14:48 UTC, afkir01 approved these changes

2018-01-18 14:49 UTC, afkir01 approved these changes

2018-01-18 14:50 UTC, AvantHof approved these changes

2018-01-18 14:53 UTC, merged