Feature available rooms endpoint
Cap-SE-Training/Hotel pull request #20
Opened 2018-01-26 11:33 UTC by nielsopdam

Added an API endpoint and repository search functions for rooms.

2018-01-29 14:08 UTC, AvantHof requested changes

2018-01-29 14:08 UTC, AvantHof commented on src/main/java/com/capgemini/setrack/controller/RoomController.java
> +            @RequestParam(name="size", required=false) Integer size,
Integer hoofdletter I? De klasse ipv het primitieve datatype?

2018-01-29 14:08 UTC, AvantHof commented on src/main/java/com/capgemini/setrack/controller/RoomController.java
> +            @RequestParam(name="room_type_id", required=false) Long room_type_id) {
Zelfde als bij integer, primitieve datatype vs klasse

2018-01-29 14:08 UTC, AvantHof commented on src/main/java/com/capgemini/setrack/repository/RoomRepository.java
> +                                                  @Param("room_type_id") long room_type_id);
Hier vraag je om een long room_type_id en in de controller vraag je om een Long room_type_id, consistentie!!!!!

2018-01-29 14:08 UTC, AvantHof commented on src/main/java/com/capgemini/setrack/repository/RoomRepository.java
> +    @Query("SELECT r1 FROM Room r1 WHERE r1.id NOT IN " +
Evt een comment met wat uitleg wat de query verwacht / doet?

2018-02-05 14:17 UTC, jimmy1993k approved these changes

2018-02-06 09:35 UTC, AvantHof approved these changes

2018-02-06 10:18 UTC, AvantHof approved these changes

2018-02-06 10:27 UTC, merged