Feature demo sprint2
Cap-SE-Training/Hotel pull request #22
Opened 2018-01-29 14:58 UTC by nielsopdam

Small fixes in front end of bookings.
Added minty.css file

2018-01-29 15:29 UTC, jimmy1993k commented on src/main/resources/public/js/bookings.js
> +        url:"/api/booking/",
/api/bookings/

2018-01-29 15:29 UTC, jimmy1993k commented on src/main/resources/public/js/bookings.js
>              console.log("This is the data: " + bookings);
console.log kan weg

2018-01-29 15:30 UTC, jimmy1993k reviewed
check comments

2018-01-29 15:33 UTC, AvantHof requested changes

2018-01-29 15:33 UTC, AvantHof commented on src/main/resources/public/js/bookings.js
> +            { "mData": function date(data, type, dataToSet) {
wat is mData?

2018-01-29 15:33 UTC, AvantHof commented on src/main/resources/public/js/bookings.js
> +            { "mData": function date(data, type, dataToSet) {
Tijdstip ipv hele datum

2018-01-29 15:33 UTC, AvantHof commented on src/main/resources/public/js/bookings.js
>      console.log("Getting All Bookings...");
console.log kan weg

2018-01-30 10:02 UTC, AvantHof approved these changes

2018-01-30 10:03 UTC, merged